#!/bin/zsh

# CREATE HEROKU APP
if [[ "${1}" == "1" ]]
then
   echo "*** creating heroku app ***";
   heroku create gutibaji2;
   git remote add heroku https://github.com/navidmostafiz/NMWebRTC.git
   exit 1;
# DEPLOY AND START APP ON HEROKU
elif [[ "${1}" == "2" ]]
then
   echo "*** deploying latest git push to heroku ***";
   git push heroku master;
   echo "*** starting 1 app instance on heroku ***";
   heroku ps:scale web=1 -a webrtc;
   heroku open;
   # heroku logs --tail;
   exit 1;

# STOP APP ON HEROKU
elif [[ "${1}" == "3" ]]
then
   echo "*** stopping all app instances on heroku ***";
   heroku ps:scale web=0;
   exit 1;

else
   echo "not a heroic param given :(";
   exit 1;
fi;